### ISSUE TITLE
Create workflow-cli(-pr) jobs

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#125]
After https://github.com/deis/jenkins-jobs/pull/124 we are set up to build out `workflow-cli(-pr)` jobs.  They won't necessarily follow most of the common logic in the existing `component_jobs.groovy` and the build/(unit) test/deploy logic is handled currently by travis/appveyor, so we just want jobs to get kicked off on commits to master/PR branches (respectively) and hand the commit sha, when applicable (for PRs) to the downstream e2e test job.

TODOs
- [ ] ~~remove the line [here](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_test.groovy#L92) as the env var will be auto-generated and passed to the downstream test job when these new jobs are created.~~

**Comment by arschles** [comment]
Proposal:
1. Pin to commits on the deis SDK repo in the CLI's glide.yaml (https://github.com/deis/workflow-cli/pull/108)
2. When a PR is submitted on the CLI, make this job:
   1. Download the CLI source
   2. Modify the `glide.yaml` locally (not in the PR) to point to the latest commit on the fork & branch represented by the PR
      - This should be done with a tool that calculates the new SHA, parses the `glide.yaml` and inserts the repo alias & new commit
   3. Build the CLI locally with the new dependencies pointed to by the glide.yaml
   4. Run e2e tests as normal
3. Add a new job for [SDK](https://github.com/deis/controller-sdk-go) PRs, which does the following when a PR is submitted to it:
   1. Download the CLI source
   2. Modify the `glide.yaml` locally (not in the PR) to point to the latest commit on the fork & branch represented by the submitted PR
      - This should be done with the same tool as referenced in 2.2
   3. Build the CLI locally with the new dependencies pointed to by the glide.yaml
   4. Run e2e tests as normal

**Comment by Joshua-Anderson** [comment]
I opened deis/workflow#359 to discuss the different testing strategies, and we can leave this issue for the general jenkins configuration work required with settings up CI on the repositories.

**Comment by vdice** [comment]
`workflow-cli` and `controller-sdk-go` Jenkinsfiles were added as of https://github.com/deis/workflow-cli/pull/112 and https://github.com/deis/controller-sdk-go/pull/31.  Subsequent e2e-related PRs/issues will be created per https://github.com/deis/workflow/issues/359.  Closing.
