### ISSUE TITLE
workflow-cli-release job

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#135]
Unfortunately, it doesn't appear that a Jenkinsfile-based pipeline is able to trigger a build off of a git tag (see https://issues.jenkins-ci.org/browse/JENKINS-34395).  Therefore, at this time, we require a `workflow-cli-release` job that will act similarly to the existing `<component>_release` [job](https://github.com/deis/jenkins-jobs/blob/master/jobs/component_release.groovy) in that it watches the current `release-${WORKFLOW_RELEASE}` branch for push events and then triggers a build/deployment of the appropriate release artifact -- in this case the `workflow-cli` binary/binaries.

TODO
- [ ] PR in https://github.com/deis/deisrel to add `workflow-cli` to the list used in the creation of release branches (see https://github.com/deis/deisrel/blob/92670ea2b94df2c71010eab4436092be3b233437/actions/common.go#L54 and ensure these are used in said action)

**Comment by vdice** [comment]
@Joshua-Anderson is it acceptable for a given release binary to be overwritten/re-deployed if the release branch in the `workflow-cli` repo is pushed to multiple times?

Also, do we require this job to build and deploy all cross-compiled binaries -- or just as subset?

**Comment by Joshua-Anderson** [comment]
Overwriting the binary is fine. This job needs to build every binary and architecture.
