### ISSUE TITLE
Revisit slack notification if workflow-test fails

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#162]
https://github.com/deis/jenkins-jobs/issues/155 adds a job to promote a component image to the production 'deis' registry org.  If the upstream `workflow-test` job fails on a master merge for a component, there is added importance to resolve this issue as the next release for said component will attempt to use this promoted image as a release candidate.

Currently there are slack notifications being sent (to the #testing channel) if the `workflow-test` job fails.  The message only contains a test report link and an upstream job link... perhaps it would be good to explicitly mention the change author of the merge commit?

If via `git` cli, it would be something like `git rev-parse HEAD | git --no-pager show -s --format='%an <%ae>'`.  

Alternatively, we should also be able to get `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` from the upstream component merge job, assuming we pass those vars down...

**Comment by vdice** [comment]
@jchauncey I was just going to add the commit author name to the existing slack notification -- or do you have any other idea(s) on an effective approach towards alerting/raising awareness on a master merge failure (so the release candidate won't be promoted to the 'deis' registry orgs)

**Comment by jchauncey** [comment]
I like author name FWIW
