### ISSUE TITLE
builder e2e failing exporting env.properties

### ISSUE THREAD

**Issue by bacongobbler** [deis/jenkins-jobs#172]
https://ci.deis.io/job/builder-pr/287/console

```
12:00:33 /tmp/hudson5162959604179303883.sh: line 6: export: `<mfisher@deis.com>': not a valid identifier
```

The error seems point to https://github.com/deis/jenkins-jobs/blob/a50e0c2f4ce467a36cc590c093d50eaf1655e3da/jobs/component_jobs.groovy#L123

**Comment by vdice** [comment]
Apologies, had unintentionally introduced a PR'd DSL change which introduced this error.  Fixed by running the 'master' branch of all job DSLs via https://ci.deis.io/job/seed-job/ 

@bacongobbler please try to rerun the failed job(s).

**Comment by bacongobbler** [comment]
e2e builds are now moving along smoothly. Thanks for the quick response!
