### ISSUE TITLE
Component release e2e strategy

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#174]
https://github.com/deis/jenkins-jobs/issues/158 rolled out the initial iteration of a component release pipeline.  The e2e stage of this pipeline simply retrieved the last released `workflow-<release>` chart, plugged in the release candidate for its respective component docker tag and ran that against the `workflow-<release>-e2e` chart.

The drawback to this approach is other components may have released in the interim since the last released workflow chart.  For the most accurate test results, we would want an up-to-date `workflow` chart wherein all components' docker tags are the very latest semver tags straight from git or image registry.  

To save manual effort from having to look up each component's latest semver tags, a corresponding tool would need to be made (perhaps in https://github.com/deis/deisrel) that could ping either the GitHub API or Quay.io/DockerHub API to derive each component's latest semver tag and produce the chart used for testing...

**Comment by Joshua-Anderson** [comment]
It would be pretty trivial to add an option to `deisrel` that after looking up tag versions would edit the `generate_params.toml` file with the latest versions. Should I implement that?

**Comment by vdice** [comment]
@Joshua-Anderson Indeed, I think that would be a great option for us, at least for the API/`generate_params.toml` update portion.  Thinking on it more, our current e2e infra (specifically the logic in https://github.com/deis/e2e-runner) doesn't yet really support plugging in a chart on-demand.  (Rather it fetches and installs charts from a git remote.)  So, I think there may be another sibling chunk of work to enable 'passing' a chart to install to e2e-runner... unless there might be a better way?
