### ISSUE TITLE
CI Status set as passing for builds that actually fail

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/jenkins-jobs#197]
I've seen this happen on several builds. This is really dangerous because it makes it easy to miss legitimate CI errors and break e2e.

https://ci.deis.io/job/workflow-test-pr/4878/console

**Comment by vdice** [comment]
The crucial bit appears to be the test pod exiting 0 despite the non-zero `make` target exit code:

```
...
10:52:58 make: *** [test-integration] Error 1
10:52:58 Test pod exited with code:0
...
```
