### ISSUE TITLE
golang-based build jobs hang

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#209]
Golang-based components (read: most/all(?) Workflow components) that happen to run build jobs on nodes with `vendor` dirs still owned by root  (from running `glide install` on the node host previously) will hang indefinitely.

The manual fix is to hop on the node, `cd` to that job's workspace and `sudo rm -rf vendor/` -- assuming you happen to be watching the build job.

The actual fix, or at least the most preferable at time of writing, would be to run `glide install` inside of a container, thereby avoiding actually touching the node host itself.  Consider the example set in https://github.com/deis/workflow-cli/pull/181.  The trick would be to generalize this approach so that any job can use this pattern w/o duplicating code.  (Possibly related is the effort of extracting common job DSL logic in https://github.com/deis/workflow-cli/issues/142 -- though not sure if it only applies to Pipelines)

**Comment by Joshua-Anderson** [comment]
One solution we could use is run our jobs within docker containers instead on the VM itself. Jenkins has good docker support, but I don't know how well docker-in-docker works for those.

That way we could be sure no state was persisted.

**Comment by vdice** [comment]
@Joshua-Anderson good point.  Recording a relevant link here: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by vdice** [comment]
Temporary/quick fix added in https://github.com/deis/ci-manager/pull/8.  We can revisit if/when a more complete solution is desired.
