### ISSUE TITLE
Create claim cluster job DSL

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#23]
This job should run the logic needed to claim a k8s cluster for use by the downstream [e2e test job](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_test.groovy).  

Reference the [meta issue](https://github.com/deis/jenkins-jobs/issues/20) for upstream/downstream configuration.

**Comment by vdice** [comment]
@arschles when ready, let's update this ticket with what actions this job will need to perform so that the result is a cluster is leased and ready for the downstream e2e test job to use.

**Comment by vdice** [comment]
k8s-claimer work was not forecast in the beta4 effort, therefore moving on to rc1 milestone

**Comment by arschles** [comment]
@vdice @jchauncey since the e2e job is now using the k8s-claimer, I believe we can close this. Am I wrong?

**Comment by vdice** [comment]
Thanks @arschles for pointing this out; closing.
