### ISSUE TITLE
Report workflow-test SUCCESS to slack

### ISSUE THREAD

**Issue by sgoings** [deis/jenkins-jobs#236]
Let's enable workflow-test SUCCESS reporting back to Slack. This functionality was originally removed via #207 when life was a bit crazy for CI... but now I think we need to raise visibility (via our slack channel) of how stable/successful e2e tests on master actually are.

This is definitely not a perfect solution... but I'd like to see if turning these notifications on help calm our anxiety of CI/e2e instability.

Also willing to discuss better/longer-term solutions here! /cc @mboersma @helgi

**Comment by mboersma** [comment]
Agree 💯. It's hard to get a sense of things when we only report failures. If it's possible to make successes short one-liners, but preserve the detail on failures, that might be a happy medium of signal to noise.
