### ISSUE TITLE
Create cluster cleanup job DSL

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#24]
This job should run the logic needed to 'clean up' a k8s cluster after the upstream  [e2e test job](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_test.groovy) finishes (regardless of build status.)

Reference the [meta issue](https://github.com/deis/jenkins-jobs/issues/20) for upstream/downstream configuration.

**Comment by vdice** [comment]
k8s-claimer work was not forecast in the beta4 effort, therefore moving on to rc1 milestone

**Comment by arschles** [comment]
@vdice @jchauncey since the e2e job is now using the k8s-claimer, I believe we can close this. Am I wrong?

**Comment by vdice** [comment]
I believe you are right @arschles , thanks for pointing this out.  Closing.
