### ISSUE TITLE
deis-seed-repos job failing

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#249]
https://ci.deis.io/job/deis-seed-repos/40/console

Note the following two failures:

> 10:29:13 /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/deis/cloudfoundry-github-service-broker-ruby/labels: 404 - Not Found // See: https://developer.github.com/v3/issues/labels/#create-a-label (Octokit::NotFound)

and

> 10:43:15 /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': PUT https://api.github.com/teams/1539687/repos/deis/workflow-manager-api-publish: 403 - You must have administrative rights on this repository. // See: https://developer.github.com/v3/orgs/teams/#add-team-repo (Octokit::Forbidden)

**Comment by vdice** [comment]
Note that it appears that all tracked `deis` repos are in fact successfully updated with the latest values in https://github.com/deis/seed-repo after the job runs, even if it does fail as above...

**Comment by bacongobbler** [comment]
Is workflow-manager-api-publish still failing? I just updated the permissions for that repo. We'll have to do the same for cloudfoundry-github-service-broker-ruby or [add it to the exemption list](https://github.com/deis/seed-repo/pull/40).

**Comment by bacongobbler** [comment]
looks like it's the same issue as megaboom for that repo; issues aren't enabled because it's a forked project and we aren't going to be maintaining it actively, so I think it's a candidate to the exemption list.

**Comment by vdice** [comment]
@bacongobbler it looks like the job is happy now (https://ci.deis.io/job/deis-seed-repos/42/console) which makes sense for the wfm-api-publish permissions amendment but kinda odd when https://github.com/deis/seed-repo/pull/43 is still open!
