### ISSUE TITLE
PR's with chart changes are not tested properly

### ISSUE THREAD

**Issue by kmala** [deis/jenkins-jobs#308]
When a PR with chart changes is created, the jenkins is not creating charts with the changes in that PR.
PR with chart changes: https://github.com/deis/router/pull/296 
chart publish job : https://ci.deis.io/view/component%20chart%20publish%20jobs/job/router-chart-publish/24/console
If you download the router chart `helm fetch routerpr/router --version v2.7.1-20161222170241-sha.0fae6d1 --untar` created in that job, it doesn't have the changes in the PR

cc @vdice

**Comment by vdice** [comment]
Great catch, @kmala !  Check out https://github.com/deis/jenkins-jobs/pull/310 for the fix.
