### ISSUE TITLE
release ci: Workflow staging chart approach

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#319]
In testing a Workflow release candidate chart, it is often the case that additional component fixes need to make it in and a new chart created with the same chart artifact filename, say, `workflow-v2.10.0.tgz`.  We currently do not have cache control on these artifact files, so CloudFront will cache for the default period (24h?)  Therefore, when one runs `helm repo up && helm upgrade <release> workflow-staging/workflow`, one may get an older/cached version.

A handful of options:

1. Simply set `--cache-control max-age=0` on the artifact if chart repo is the `-staging` variant

2. Rename the artifact with an additional `-rc1` or other.  Yet, since we copy the same candidate artifact over to the production repo (sans `index.yaml` so not yet fetch-able), we'd need to always push the official `v2.10.0` version through ci _after_ the `v2.10.0-rc*` variant had been approved for release, potentially introducing unintended changes.

3. Continue manually running CloudFront cache invalidations when/where necessary

**Comment by bacongobbler** [comment]
I think we all came to the same agreement that solution 1 looked the best for our staging environment. 👍
