### ISSUE TITLE
Generic e2e pipeline for other cloud providers

### ISSUE THREAD

**Issue by mboersma** [deis/jenkins-jobs#334]
Build a generic Workflow e2e pipeline that can:
- Spin up non-GKE k8s provider cluster (support AWS, Azure.. other?)
- Install current release Workflow
- Install current release Workflow-e2e chart
- Tear down, report test results, etc.
- This will initially be intended to be run during Workflow release time.

Notes:
- Tackle Azure first?

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/jenkins-jobs#8
