### ISSUE TITLE
Containerize Windows agent

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#351]
The Windows agent previously used in some projects came in the form of a VM w/ dependencies set up by hand.

Moving forward, we should containerize this agent so it may be deployed in a repreatable manner via a k8s cluster equipped with Windows nodes.

**Comment by kingdonb** [comment]
Any chance we can get some final closure on this?  A lot of my potential Workflow users are Windows users, and they might like to fix the windows client up eventually, but I'm not sure where to point them for build dependencies as I've been mostly using either Linux and Mac for 20 years.

If you may have a snapshot or script, or can point me at a document, then you can close this and I'll move it over to teamhephy/jenkins-jobs#2

(Thank you so much for these jenkins-jobs from Team Hephy, by the way!)

**Comment by vdice** [comment]
@kingdonb this ticket was never picked up/started; therefore, unfortunately, I don't have any scripts or Dockerfile(s) to offer.  I'll close this issue as it appears the current needs are being tracked in https://github.com/teamhephy/jenkins-jobs/issues/2.  Apologies and good luck!

**Comment by kingdonb** [comment]
No worries!  My efforts with the seed-job and Jenkins jobs appear to have actually produced a Windows binary (somehow! must be cross-compiled)

Thanks again!
