### ISSUE TITLE
Integrate k8s-claimer to claim clusters, instead of creating and tearing down a k8s cluster on each run

### ISSUE THREAD

**Issue by arschles** [deis/jenkins-jobs#51]
This change will allow tests to acquire a clean k8s cluster very quickly, instead of creating and tearing down a cluster on each run. See https://github.com/deis/k8s-claimer for more details on the claimer

**Comment by vdice** [comment]
See also #23 and #24

**Comment by arschles** [comment]
Punting to beta4 cc/ @vdice

**Comment by arschles** [comment]
Moving to RC1, as we haven't had time to focus on the claimer this sprint

**Comment by arschles** [comment]
@vdice @jchauncey since the e2e job is now using the k8s-claimer, I believe we can close this. Am I wrong?

**Comment by jchauncey** [comment]
Yeah
